---
- hosts: web
  tasks:
    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - apt-transport-https 
        - ca-certificates 
        - curl 
        - gnupg-agent 
        - software-properties-common 
    - name: Install key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: Add respository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Install Docker
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: Ensure docker service is running
      service:
        name: docker
        state: started
