---
- name: install apache
  apt:
    name: "{{ package1 }}"
    state: present
  notify: restart apache2
  tags: apache2
- name: copy index
  template:
    src: index.html.j2123
    dest: /var/www/html/index.html
  ignore_errors: yes
  tags: template
- name: copy using file
  copy:
    src: index.html.j2
    dest: /tmp
  ignore_errors: yes
